Repository bregenz-bewegt/bregenz-bewegt, pull requests merged in 2022-11, with the labels that each got.

#107 Add IOS script to run on native IOS devices
  apps/client/project.json
  package.json
Labels: architecture

#105 Consider public preference option for leadboard display
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
Labels: enhancement, backend

#100 Enhancement/94 remove unused profile pics
  prisma/seed.ts
Labels: enhancement, backend, database

#103 Removed borders from inputs
  libs/client/ui/components/src/lib/input/input.scss
  libs/client/ui/components/src/lib/item-group/item-group.scss
  libs/client/ui/pages/src/lib/start/start.scss
Labels: enhancement, good first issue, frontend, suggestion

#93 Activity Backend
  apps/server/src/app/app.module.ts
  libs/client/common/hooks/src/lib/index.ts
  libs/client/common/hooks/src/lib/useDefaultErrorToast.ts
  libs/client/common/stores/src/lib/activity.store.ts
  libs/client/common/stores/src/lib/leaderboard.store.ts
  libs/client/common/stores/src/lib/park.store.ts
  libs/client/types/src/lib/entities/activity.ts
  libs/client/types/src/lib/entities/index.ts
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/client/ui/pages/src/lib/profile/difficulty/difficulty.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/profile/public-profile/public-profile.tsx
  libs/client/ui/pages/src/lib/reset-password/reset-password.tsx
  libs/server/controllers/activity/.babelrc
  libs/server/controllers/activity/.eslintrc.json
  libs/server/controllers/activity/README.md
  libs/server/controllers/activity/jest.config.ts
  libs/server/controllers/activity/project.json
  libs/server/controllers/activity/src/index.ts
  libs/server/controllers/activity/src/lib/activity.controller.spec.ts
  libs/server/controllers/activity/src/lib/activity.controller.ts
  libs/server/controllers/activity/src/lib/activity.module.ts
  libs/server/controllers/activity/src/lib/activity.service.spec.ts
  libs/server/controllers/activity/src/lib/activity.service.ts
  libs/server/controllers/activity/tsconfig.json
  libs/server/controllers/activity/tsconfig.lib.json
  libs/server/controllers/activity/tsconfig.spec.json
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/park/src/lib/park.service.ts
  libs/shared/types/src/lib/dto/activity/end-activity.dto.ts
  libs/shared/types/src/lib/dto/activity/index.ts
  libs/shared/types/src/lib/dto/activity/start-activity.dto.ts
  libs/shared/types/src/lib/dto/index.ts
  libs/shared/types/src/lib/dto/leaderboard/get-competitor.dto.ts
  libs/shared/types/src/lib/dto/leaderboard/index.ts
  libs/shared/types/src/lib/types/index.ts
  libs/shared/types/src/lib/types/leaderboard/filter-timespans.ts
  libs/shared/types/src/lib/types/leaderboard/index.ts
  libs/shared/types/src/lib/types/leaderboard/leaderboard.ts
  libs/shared/types/src/lib/types/user/index.ts
  libs/shared/types/src/lib/types/user/with-coins.ts
  prisma/migrations/20221101143000_outsource_coins/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  tsconfig.base.json
  workspace.json
Labels: enhancement, frontend, backend, database

#117 Smooth exercise detail tab display toggle
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
Labels: bug, frontend

#118 Fix `deleteUnusedProfileImg()` in prisma seed
  prisma/seed.ts
Labels: bug, backend, database

#123 Show initial Timespan filter value
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
Labels: bug, frontend

#121 Prize Draw Information
  libs/client/ui/components/src/lib/coin-depot/coin-depot.scss
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/rewards/rewards.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
Labels: bug, enhancement, frontend

#126 Added `Activity <-> Park` database relation (1:1
  libs/server/controllers/activity/src/lib/activity.service.ts
  prisma/migrations/20221104223150_activity_park/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement, backend, database

#129 Fix activity park relation prisma schema syntax
  prisma/migrations/20221105112906_activity_park/migration.sql
  prisma/schema.prisma
Labels: bug, backend, architecture, database

#137 Fix/127 test lint pipeline
  libs/client/common/http/src/lib/http.spec.ts
  libs/client/common/stores/src/lib/park.store.ts
  libs/client/ui/components/src/index.ts
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/server/controllers/activity/src/lib/activity.controller.spec.ts
  libs/server/controllers/activity/src/lib/activity.service.spec.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.spec.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.module.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.service.spec.ts
Labels: bug, architecture

#132 Map view
  apps/client/src/theme/variables/ionic.scss
  libs/client/common/stores/src/lib/onboarding.store.ts
  libs/client/types/src/lib/entities/coordinates.ts
  libs/client/types/src/lib/entities/index.ts
  libs/client/types/src/lib/entities/park.ts
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/quick-filter/quick-filter.scss
  libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
  libs/client/ui/components/src/lib/transition-block/transition-block.scss
  libs/client/ui/components/src/lib/transition-block/transition-block.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/preferences/preferences.scss
  libs/client/ui/pages/src/lib/onboarding/slides/preferences/preferences.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.scss
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/client/ui/pages/src/lib/register/register.tsx
  libs/client/ui/pages/src/lib/start/list/list.scss
  libs/client/ui/pages/src/lib/start/list/list.tsx
  libs/client/ui/pages/src/lib/start/map/img/location-sharp.png
  libs/client/ui/pages/src/lib/start/map/map.scss
  libs/client/ui/pages/src/lib/start/map/map.tsx
  libs/client/ui/pages/src/lib/start/start.scss
  libs/client/ui/pages/src/lib/start/start.tsx
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/park/src/lib/park.service.ts
  libs/server/controllers/user/src/lib/user.service.ts
  package-lock.json
  package.json
  prisma/seed.ts
Labels: enhancement, frontend, backend

#141 Remove Transition block gradient
  libs/client/ui/components/src/lib/transition-block/transition-block.scss
Labels: bug, frontend

#53 Add Change-Email functionality to profile settings
  .example.env
  apps/client/project.json
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/common/validation/src/lib/schemas/change-email.ts
  libs/client/common/validation/src/lib/schemas/index.ts
  libs/client/common/validation/src/lib/schemas/profile.ts
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/profile/email/email.tsx
  libs/client/ui/pages/src/lib/profile/index.ts
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/register/register.tsx
  libs/client/ui/pages/src/lib/start/list/list.tsx
  libs/client/ui/pages/src/lib/verify-email/verify-email.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/server/common/src/lib/guards/email-reset.guard.ts
  libs/server/common/src/lib/guards/index.ts
  libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
  libs/server/controllers/auth/src/lib/auth.module.ts
  libs/server/controllers/auth/src/lib/auth.service.spec.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/server/controllers/user/src/lib/passport/index.ts
  libs/server/controllers/user/src/lib/passport/strategies/email-reset-token.strategy.ts
  libs/server/controllers/user/src/lib/passport/strategies/index.ts
  libs/server/controllers/user/src/lib/user.controller.spec.ts
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/server/controllers/user/src/lib/user.module.ts
  libs/server/controllers/user/src/lib/user.service.spec.ts
  libs/server/controllers/user/src/lib/user.service.ts
  libs/server/util/src/lib/util.service.ts
  libs/shared/errors/src/lib/index.ts
  libs/shared/errors/src/lib/login-error.ts
  libs/shared/errors/src/lib/reset-email-error.ts
  libs/shared/types/src/lib/dto/user/index.ts
  libs/shared/types/src/lib/dto/user/reset-email.dto.ts
  libs/shared/types/src/lib/dto/user/verify-reset-email.dto.ts
  libs/shared/types/src/lib/types/user/email-reset-token.ts
  libs/shared/types/src/lib/types/user/index.ts
  prisma/migrations/20221108073204_email_reset_token/migration.sql
  prisma/schema.prisma
Labels: enhancement, help wanted, frontend, backend

#87 Serve profile images as static files
  .example.env
  .gitignore
  apps/client/project.json
  apps/server/project.json
  apps/server/src/app/app.module.ts
  libs/client/common/http/src/lib/http.ts
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/server/controllers/user/src/lib/user.service.ts
  libs/server/multer/src/lib/multer.service.ts
  prisma/seed.ts
  static/.gitkeep
Labels: help wanted, backend, architecture, refactoring, urgent

#145 Refactor password change
  apps/client/project.json
  apps/server/project.json
  libs/client/common/stores/.eslintrc.json
  libs/client/common/stores/src/lib/activity.store.ts
  libs/client/common/stores/src/lib/exercise.store.ts
  libs/client/common/stores/src/lib/onboarding.store.ts
  libs/client/common/stores/src/lib/park.store.ts
  libs/client/common/stores/src/lib/tab.store.ts
  libs/client/common/stores/src/lib/theme.store.ts
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/common/validation/src/lib/schemas/change-password.ts
  libs/client/common/validation/src/lib/schemas/index.ts
  libs/client/ui/pages/src/lib/profile/email/email.tsx
  libs/client/ui/pages/src/lib/profile/index.ts
  libs/client/ui/pages/src/lib/profile/password/password.scss
  libs/client/ui/pages/src/lib/profile/password/password.tsx
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/auth/src/lib/auth.module.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/shared/errors/src/lib/change-password-error.ts
  libs/shared/errors/src/lib/index.ts
  libs/shared/types/src/lib/dto/auth/change-password.dto.ts
  libs/shared/types/src/lib/dto/auth/index.ts
Labels: frontend, backend, refactoring

#153 Style changes
  libs/client/ui/components/src/lib/back-button/back-button.scss
  libs/client/ui/components/src/lib/back-button/back-button.tsx
  libs/client/ui/components/src/lib/difficulty-badge/difficulty-badge.scss
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/park-card/park-card.scss
  libs/client/ui/components/src/lib/park-card/park-card.tsx
  libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
  libs/client/ui/components/src/lib/transition-block/transition-block.scss
  libs/client/ui/components/src/lib/transition-block/transition-block.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.scss
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.scss
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/reset-password/reset-password.tsx
  libs/client/ui/pages/src/lib/start/list/list.scss
  libs/client/ui/pages/src/lib/start/list/list.tsx
  libs/client/ui/pages/src/lib/start/map/map.scss
  libs/client/ui/pages/src/lib/start/map/map.tsx
Labels: enhancement, frontend

#159 Assign CUIDs as usernames for guest users
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/server/controllers/auth/src/lib/auth.service.ts
  package-lock.json
  package.json
  prisma/migrations/20221114155238_guest_fingerprint/migration.sql
  prisma/schema.prisma
Labels: frontend, backend, refactoring, database

#157 Add Capacitor appId
  apps/client/capacitor.config.ts
Labels: enhancement, architecture

#151 Seed Production Content
  apps/client/src/App.tsx
  libs/client/common/hooks/src/lib/useDefaultErrorToast.ts
  libs/client/common/stores/src/lib/exercise.store.ts
  libs/client/types/src/lib/entities/exercise.ts
  libs/client/types/src/lib/entities/park.ts
  libs/client/ui/components/src/lib/activity-timer/activity-timer.scss
  libs/client/ui/components/src/lib/activity-timer/activity-timer.tsx
  libs/client/ui/components/src/lib/exercise-card/exercise-card.scss
  libs/client/ui/components/src/lib/exercise-card/exercise-card.tsx
  libs/client/ui/components/src/lib/header/header.scss
  libs/client/ui/components/src/lib/park-card/park-card.scss
  libs/client/ui/components/src/lib/park-card/park-card.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.scss
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/start/map/map.tsx
  libs/client/ui/pages/src/lib/start/start.tsx
  libs/server/controllers/exercise/src/lib/exercise.service.ts
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/park/src/lib/park.service.ts
  package.json
  prisma/migrations/20221111165608_exercise_text/migration.sql
  prisma/migrations/20221111200941_park_gmaps/migration.sql
  prisma/migrations/20221113144710_prod_seed_fix/migration.sql
  prisma/migrations/20221114103710_exercise_description_split/migration.sql
  prisma/schema.prisma
  prisma/seed.prod.ts
  prisma/seed.purge.ts
  prisma/seed.ts
Labels: enhancement, frontend, backend, urgent

#165 Hide Leaderboard for Guest
  libs/client/common/hooks/src/lib/default-error-toast.ts
  libs/client/common/hooks/src/lib/index.ts
  libs/client/common/hooks/src/lib/is-guest.ts
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/components/src/lib/guest-lock/guest-lock.scss
  libs/client/ui/components/src/lib/guest-lock/guest-lock.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
Labels: enhancement, frontend, refactoring

#169 Show profile pictures in leaderboard
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/server/controllers/leaderboard/src/lib/leaderboard.service.ts
  libs/shared/types/src/lib/types/leaderboard/leaderboard.ts
Labels: enhancement, frontend

#170 Fix NPM vulnerabilities
  package-lock.json
Labels: architecture

#161 Create Statistic page
  libs/client/common/stores/src/lib/activity.store.ts
  libs/client/types/src/lib/entities/activity.ts
  libs/client/types/src/lib/types/activity-chart-data.ts
  libs/client/types/src/lib/types/index.ts
  libs/client/ui/components/src/lib/activity-card/activity-card.scss
  libs/client/ui/components/src/lib/activity-card/activity-card.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/pages/src/lib/analytics/analytics.scss
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
  libs/server/controllers/activity/src/lib/activity.controller.ts
  libs/server/controllers/activity/src/lib/activity.service.ts
  libs/shared/types/src/lib/dto/activity/activity-pagination.dto.ts
  libs/shared/types/src/lib/dto/activity/index.ts
  package-lock.json
  package.json
  prisma/seed.ts
Labels: enhancement, frontend, backend

#188 Change park detail filter
  libs/client/ui/components/src/lib/quick-filter/quick-filter.scss
  libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.scss
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
Labels: enhancement, frontend
