Repository bregenz-bewegt/bregenz-bewegt, pull requests merged in 2022-10, with the labels that each got.

#65 Onboarding Slides
  apps/client/src/assets/images/.gitkeep
  libs/client/common/stores/src/lib/index.ts
  libs/client/common/stores/src/lib/onboarding.store.ts
  libs/client/ui/components/src/lib/coin-depot/coin-depot.scss
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/components/src/lib/coin/coin.scss
  libs/client/ui/components/src/lib/coin/coin.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/medal/medal.scss
  libs/client/ui/components/src/lib/medal/medal.tsx
  libs/client/ui/components/src/lib/quick-filter/index.ts
  libs/client/ui/components/src/lib/quick-filter/quick-filter-option.ts
  libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
  libs/client/ui/components/src/lib/store-provider/store-provider.tsx
  libs/client/ui/components/src/lib/title-banner/title-banner.scss
  libs/client/ui/components/src/lib/title-banner/title-banner.tsx
  libs/client/ui/pages/src/index.ts
  libs/client/ui/pages/src/lib/forgot-password-email-sent/forgot-password-email-sent.scss
  libs/client/ui/pages/src/lib/forgot-password-email-sent/forgot-password-email-sent.tsx
  libs/client/ui/pages/src/lib/index.ts
  libs/client/ui/pages/src/lib/intro/intro.scss
  libs/client/ui/pages/src/lib/intro/intro.tsx
  libs/client/ui/pages/src/lib/onboarding/onboarding.scss
  libs/client/ui/pages/src/lib/onboarding/onboarding.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/earn/earn.scss
  libs/client/ui/pages/src/lib/onboarding/slides/earn/earn.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/index.ts
  libs/client/ui/pages/src/lib/onboarding/slides/intro/intro.scss
  libs/client/ui/pages/src/lib/onboarding/slides/intro/intro.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/preferences/preferences.scss
  libs/client/ui/pages/src/lib/onboarding/slides/preferences/preferences.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/rewards/rewards.scss
  libs/client/ui/pages/src/lib/onboarding/slides/rewards/rewards.tsx
  libs/client/ui/router/src/lib/public-outlet/public-outlet.tsx
  libs/client/ui/router/tsconfig.lib.json
Labels: enhancement, frontend

#67 Disable Profile Scroll when locked
  libs/client/ui/components/src/lib/input/input.scss
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/register/register.tsx
Labels: bug, frontend

#69 Park card styling
  libs/client/ui/components/src/lib/park-card/park-card.scss
  libs/client/ui/components/src/lib/park-card/park-card.tsx
  libs/client/ui/pages/src/lib/start/start.scss
Labels: frontend

#71 Darkmode bug fixes
  libs/client/ui/components/src/lib/activity-timer/activity-timer.scss
  libs/client/ui/components/src/lib/header/header.scss
Labels: bug, frontend

#77 Changed delete account label
  libs/client/ui/pages/src/lib/profile/profile.tsx
Labels: frontend

#81 Profile darkmode toggle setting
  apps/client/src/theme/variables/ionic.scss
  libs/client/common/stores/src/lib/index.ts
  libs/client/common/stores/src/lib/theme.store.ts
  libs/client/types/src/lib/enums/color-theme.ts
  libs/client/types/src/lib/enums/index.ts
  libs/client/ui/components/src/index.ts
  libs/client/ui/components/src/lib/header/header.scss
  libs/client/ui/components/src/lib/item-group/item-group.scss
  libs/client/ui/components/src/lib/item-group/item-group.tsx
  libs/client/ui/components/src/lib/store-provider/store-provider.tsx
  libs/client/ui/pages/src/index.ts
  libs/client/ui/pages/src/lib/appearance/appearance.scss
  libs/client/ui/pages/src/lib/appearance/appearance.tsx
  libs/client/ui/pages/src/lib/index.ts
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/client/ui/shared/content/src/lib/index.ts
  libs/client/ui/shared/content/src/lib/themeDisplayTexts.ts
Labels: enhancement, frontend

#84 Enhance database seed data
  apps/client/src/theme/variables/ionic.scss
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
  libs/shared/types/src/lib/dto/leaderboard/leaderboard-pagination.dto.ts
  package-lock.json
  package.json
  prisma/seed.ts
Labels: architecture, database

#96 Leaderboard sticky self row top
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
Labels: enhancement, frontend

#57 Preferences and Rank Checkbox
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/types/src/lib/entities/difficulty.ts
  libs/client/types/src/lib/entities/exercise.ts
  libs/client/types/src/lib/entities/index.ts
  libs/client/types/src/lib/entities/preferences.ts
  libs/client/types/src/lib/entities/user.ts
  libs/client/ui/components/src/lib/difficulty-badge/difficulty-badge.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/toggle/toggle.scss
  libs/client/ui/components/src/lib/toggle/toggle.tsx
  libs/client/ui/pages/src/index.ts
  libs/client/ui/pages/src/lib/index.ts
  libs/client/ui/pages/src/lib/profile/appearance/appearance.scss
  libs/client/ui/pages/src/lib/profile/appearance/appearance.tsx
  libs/client/ui/pages/src/lib/profile/difficulty/difficulty.tsx
  libs/client/ui/pages/src/lib/profile/index.ts
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/profile/public-profile/public-profile.tsx
  libs/client/ui/pages/src/lib/start/start.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/client/ui/shared/content/src/lib/difficultyDisplayTexts.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/server/controllers/user/src/lib/user.service.ts
  libs/shared/types/src/lib/dto/user/index.ts
  libs/shared/types/src/lib/dto/user/patch-preferences.dto.ts
  prisma/migrations/20221002125831_difficulty/migration.sql
  prisma/migrations/20221005070317_public_profile/migration.sql
  prisma/migrations/20221010090714_difficulty_fix/migration.sql
  prisma/migrations/20221025154129_preference_nullable_relation/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement, frontend, backend
