Repository bregenz-bewegt/bregenz-bewegt, pull requests merged in 2022-09, with the labels that each got.

#33 Prisma Seed - New User
  apps/client/android/app/src/main/assets/capacitor.config.json
  prisma/seed.ts
Labels: enhancement, good first issue, backend, architecture

#37 Optional Register Fields
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/common/validation/src/lib/schemas/register.ts
  libs/client/types/src/lib/index.ts
  libs/client/types/src/lib/types/index.ts
  libs/client/types/src/lib/types/login-credentials.ts
  libs/client/types/src/lib/types/register-credentials.ts
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/register/register.scss
  libs/client/ui/pages/src/lib/register/register.tsx
  libs/server/common/src/lib/validation/errors/login-error.ts
  libs/server/common/src/lib/validation/errors/register-error.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/shared/types/src/lib/dto/auth/register.dto.ts
Labels: enhancement, frontend, backend

#41 TypeScript Eslint force explicit return types on functions
  .nvmrc
  apps/client/src/reportWebVitals.ts
  apps/server/src/app/app.controller.ts
  apps/server/src/main.ts
  libs/server/controllers/auth/.eslintrc.json
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/server/controllers/exercise/.eslintrc.json
  libs/server/controllers/exercise/src/lib/exercise.controller.ts
  libs/server/controllers/exercise/src/lib/exercise.service.ts
  libs/server/controllers/park/.eslintrc.json
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/park/src/lib/park.service.ts
  libs/server/controllers/user/.eslintrc.json
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/server/controllers/user/src/lib/user.service.ts
  libs/server/mail/src/lib/mail.service.ts
Labels: architecture

#47 Username in profile
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
Labels: enhancement, frontend

#45 Exercise Detail Page Style
  apps/client/android/app/src/main/assets/capacitor.config.json
  apps/client/src/theme/variables/ionic.scss
  libs/client/common/hooks/.babelrc
  libs/client/common/hooks/.eslintrc.json
  libs/client/common/hooks/README.md
  libs/client/common/hooks/jest.config.ts
  libs/client/common/hooks/project.json
  libs/client/common/hooks/src/index.ts
  libs/client/common/hooks/src/lib/index.ts
  libs/client/common/hooks/tsconfig.json
  libs/client/common/hooks/tsconfig.lib.json
  libs/client/common/hooks/tsconfig.spec.json
  libs/client/common/stores/src/lib/activity.store.ts
  libs/client/common/stores/src/lib/index.ts
  libs/client/common/stores/src/lib/park.store.ts
  libs/client/common/stores/src/lib/tab.store.ts
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/types/src/lib/index.ts
  libs/client/types/src/lib/types/activity-timer-result.ts
  libs/client/types/src/lib/types/index.ts
  libs/client/ui/components/src/lib/activity-timer/activity-timer.scss
  libs/client/ui/components/src/lib/activity-timer/activity-timer.tsx
  libs/client/ui/components/src/lib/coin-depot/coin-depot.tsx
  libs/client/ui/components/src/lib/difficulty-badge/difficulty-badge.tsx
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/store-provider/store-provider.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.scss
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/router/src/lib/router.tsx
  libs/server/controllers/auth/src/lib/passport/strategies/access-token.strategy.ts
  libs/server/controllers/exercise/src/lib/exercise.service.ts
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/park/src/lib/park.service.ts
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: enhancement, frontend

#50 Login forgot password
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/common/validation/src/lib/schemas/forgot-password.ts
  libs/client/common/validation/src/lib/schemas/index.ts
  libs/client/common/validation/src/lib/schemas/reset-password.ts
  libs/client/ui/components/src/lib/route-guard/route-guard.tsx
  libs/client/ui/pages/src/lib/email-sent/email-sent.scss
  libs/client/ui/pages/src/lib/email-sent/email-sent.tsx
  libs/client/ui/pages/src/lib/forgot-password/forgot-password.scss
  libs/client/ui/pages/src/lib/forgot-password/forgot-password.tsx
  libs/client/ui/pages/src/lib/index.ts
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/reset-password/reset-password.tsx
  libs/client/ui/router/src/index.ts
  libs/client/ui/router/src/lib/index.ts
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/client/ui/router/src/lib/public-outlet/public-outlet.tsx
  libs/client/ui/router/src/lib/router.tsx
  libs/client/ui/router/tsconfig.lib.json
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/shared/errors/src/lib/forgot-password-error.ts
  libs/shared/errors/src/lib/index.ts
  libs/shared/types/src/lib/dto/auth/forgot-password.dto.ts
  libs/shared/types/src/lib/dto/auth/index.ts
Labels: enhancement, frontend, backend

#61 Guest login
  apps/server/src/app/app.module.ts
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/ui/components/src/lib/header/header.scss
  libs/client/ui/pages/src/lib/login/login.scss
  libs/client/ui/pages/src/lib/login/login.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/scan/scan.tsx
  libs/server/common/src/lib/decorators/has-role.decorator.ts
  libs/server/common/src/lib/decorators/index.ts
  libs/server/common/src/lib/guards/index.ts
  libs/server/common/src/lib/guards/role.guard.ts
  libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/shared/types/src/lib/dto/auth/guest.dto.ts
  libs/shared/types/src/lib/dto/auth/index.ts
  libs/shared/types/src/lib/dto/auth/verify.dto.ts
  libs/shared/types/src/lib/types/auth/jwt-payload.ts
  package-lock.json
  package.json
Labels: frontend, backend

#55 Delete Account
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/server/controllers/user/src/lib/user.controller.ts
  libs/server/controllers/user/src/lib/user.service.ts
  prisma/seed.ts
Labels: enhancement, frontend, backend
