Repository bregenz-bewegt/bregenz-bewegt, pull requests merged in 2022-12, with the labels that each got.

#182 Email Theme
  apps/server/src/app/app.module.ts
  apps/server/src/assets/mail/templates/activate-mail.hbs
  apps/server/src/assets/mail/templates/change-password.hbs
  libs/client/ui/components/src/lib/title-banner/title-banner.scss
  libs/server/controllers/auth/src/lib/auth.service.ts
  libs/server/controllers/user/src/lib/user.service.ts
  libs/server/mail/src/lib/mail.service.ts
Labels: enhancement, backend

#196 Analytics load bug `onIonViewWillEnter` taking 0
  libs/client/common/stores/src/lib/user.store.ts
  libs/client/ui/components/src/lib/header/header.tsx
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/client/ui/pages/src/lib/profile/friends/add-friend-modal/add-friend-modal.tsx
  libs/client/ui/pages/src/lib/profile/friends/friend-list/friend-list.tsx
  libs/client/ui/pages/src/lib/profile/friends/request-list/request-list.tsx
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/server/common/src/lib/interceptors/index.ts
  libs/server/common/src/lib/interceptors/map-user.interceptor.ts
  libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/friend/src/lib/friend.controller.ts
  libs/server/controllers/user/src/lib/user.controller.ts
Labels: bug, frontend

#193 Capitalize type syntax
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
Labels: frontend

#201 `RemoveSensitiveFieldsInterceptor` mapping nested arrays of objects
  libs/server/common/src/lib/interceptors/map-profile-picture-path.interceptor.ts
  libs/server/common/src/lib/interceptors/remove-sensitive-fields.interceptor.ts
Labels: bug, backend

#214 Change difficulty color
  apps/client/src/theme/variables/ionic.scss
  libs/client/types/src/lib/enums/difficulty-color.ts
  libs/client/types/src/lib/enums/index.ts
  libs/client/ui/components/src/lib/difficulty-badge/difficulty-badge.tsx
  libs/client/ui/components/src/lib/quick-filter/quick-filter-option.ts
  libs/client/ui/components/src/lib/quick-filter/quick-filter.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
Labels: enhancement, frontend

#171 Implement basic video player
  libs/client/ui/components/src/lib/park-card/park-card.scss
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.scss
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/server/common/src/lib/interceptors/index.ts
  libs/server/common/src/lib/interceptors/map-park-image-path.interceptor.ts
  libs/server/common/src/lib/interceptors/map-profile-picture-path.interceptor.ts
  libs/server/common/src/lib/interceptors/map-static-asset-path.interceptor.ts
  libs/server/controllers/auth/src/lib/auth.controller.ts
  libs/server/controllers/exercise/src/lib/exercise.controller.ts
  libs/server/controllers/friend/src/lib/friend.controller.ts
  libs/server/controllers/leaderboard/src/lib/leaderboard.controller.ts
  libs/server/controllers/park/src/lib/park.controller.ts
  libs/server/controllers/user/src/lib/user.controller.ts
  prisma/seed.ts
  static/.gitkeep
Labels: enhancement, frontend

#212 Add searchbar bottom whitespace
  libs/client/ui/pages/src/lib/start/list/list.scss
  libs/client/ui/pages/src/lib/start/list/list.tsx
Labels: bug, frontend, urgent

#224 Delete account confirmation message to informal wording
  libs/client/ui/pages/src/lib/profile/profile.tsx
Labels: bug, frontend

#220 Exercise lock information for guests
  libs/client/ui/components/src/lib/activity-timer/activity-timer.tsx
Labels: enhancement, frontend

#221 Notifications page
  apps/server/src/app/app.module.ts
  libs/client/common/stores/src/lib/index.ts
  libs/client/common/stores/src/lib/notifications.store.ts
  libs/client/types/src/lib/entities/exercise.ts
  libs/client/types/src/lib/entities/index.ts
  libs/client/types/src/lib/entities/notification.ts
  libs/client/types/src/lib/entities/preferences.ts
  libs/client/types/src/lib/enums/difficulty-type.ts
  libs/client/types/src/lib/enums/index.ts
  libs/client/types/src/lib/enums/notification-type.ts
  libs/client/ui/components/src/lib/back-button/back-button.tsx
  libs/client/ui/components/src/lib/header/header.scss
  libs/client/ui/components/src/lib/header/header.tsx
  libs/client/ui/components/src/lib/item-group/item-group.tsx
  libs/client/ui/components/src/lib/store-provider/store-provider.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/index.ts
  libs/client/ui/pages/src/lib/notifications/notifications.scss
  libs/client/ui/pages/src/lib/notifications/notifications.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/server/controllers/friend/src/lib/friend.service.ts
  libs/server/controllers/notification/.babelrc
  libs/server/controllers/notification/.eslintrc.json
  libs/server/controllers/notification/README.md
  libs/server/controllers/notification/jest.config.ts
  libs/server/controllers/notification/project.json
  libs/server/controllers/notification/src/index.ts
  libs/server/controllers/notification/src/lib/notification.controller.spec.ts
  libs/server/controllers/notification/src/lib/notification.controller.ts
  libs/server/controllers/notification/src/lib/notification.module.ts
  libs/server/controllers/notification/src/lib/notification.service.spec.ts
  libs/server/controllers/notification/src/lib/notification.service.ts
  libs/server/controllers/notification/tsconfig.json
  libs/server/controllers/notification/tsconfig.lib.json
  libs/server/controllers/notification/tsconfig.spec.json
  libs/shared/types/src/lib/dto/index.ts
  libs/shared/types/src/lib/dto/notification/delete-notification.dto.ts
  libs/shared/types/src/lib/dto/notification/index.ts
  libs/shared/types/src/lib/dto/notification/mark-notification-as-read.dto.ts
  libs/shared/types/src/lib/dto/notification/mark-notification-as-unread.dto.ts
  libs/shared/types/src/lib/dto/user/patch-preferences.dto.ts
  libs/shared/types/src/lib/dto/user/patch-profile.dto.ts
  prisma/migrations/20221214170156_notification/migration.sql
  prisma/schema.prisma
  tsconfig.base.json
  workspace.json
Labels: bug, documentation, enhancement, frontend, backend, database

#236 Reset start page image max height & delete notifcations in prisma seed
  libs/client/ui/components/src/lib/park-card/park-card.scss
  prisma/seed.purge.ts
  prisma/seed.ts
Labels: bug, frontend, backend

#243 Add homepage attribute
  package.json
Labels: enhancement, good first issue, architecture

#232 Socket gateway for notification system
  apps/client/capacitor.config.ts
  apps/server/src/app/app.module.ts
  libs/client/common/socket/.babelrc
  libs/client/common/socket/.eslintrc.json
  libs/client/common/socket/README.md
  libs/client/common/socket/jest.config.ts
  libs/client/common/socket/project.json
  libs/client/common/socket/src/index.ts
  libs/client/common/socket/src/lib/index.ts
  libs/client/common/socket/src/lib/socket.ts
  libs/client/common/socket/tsconfig.json
  libs/client/common/socket/tsconfig.lib.json
  libs/client/common/socket/tsconfig.spec.json
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/notification-listener/notification-listener.tsx
  libs/client/ui/pages/src/lib/notifications/notifications.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/server/controllers/friend/src/lib/friend.controller.spec.ts
  libs/server/controllers/friend/src/lib/friend.module.ts
  libs/server/controllers/friend/src/lib/friend.service.spec.ts
  libs/server/controllers/friend/src/lib/friend.service.ts
  libs/server/gateway/.babelrc
  libs/server/gateway/.eslintrc.json
  libs/server/gateway/README.md
  libs/server/gateway/jest.config.ts
  libs/server/gateway/project.json
  libs/server/gateway/src/index.ts
  libs/server/gateway/src/lib/gateway.module.ts
  libs/server/gateway/src/lib/gateways/index.ts
  libs/server/gateway/src/lib/gateways/notification.gateway.ts
  libs/server/gateway/tsconfig.json
  libs/server/gateway/tsconfig.lib.json
  libs/server/gateway/tsconfig.spec.json
  libs/shared/types/src/lib/types/index.ts
  libs/shared/types/src/lib/types/socket/client-to-server-events.ts
  libs/shared/types/src/lib/types/socket/index.ts
  libs/shared/types/src/lib/types/socket/inter-server-events.ts
  libs/shared/types/src/lib/types/socket/server-to-client-events.ts
  package-lock.json
  package.json
  prisma/migrations/20221216074220_notification_socket/migration.sql
  prisma/schema.prisma
  prisma/seed.purge.ts
  prisma/seed.ts
  tsconfig.base.json
  workspace.json
Labels: enhancement, frontend, backend

#245 Add htaccess config
  apps/client/project.json
  apps/client/src/.htaccess
Labels: enhancement, architecture

#256 Reduce top whitespace on start page tab
  libs/client/ui/pages/src/lib/start/start.scss
Labels: frontend, refactoring

#255 Fix QR reader browser support using webrtc
  apps/client/src/main.tsx
  package-lock.json
  package.json
Labels: bug, frontend

#248 Fix custom friend list profile picture
  libs/server/controllers/friend/src/lib/friend.controller.ts
Labels: frontend, refactoring

#258 Import webrtc adapter
  apps/client/src/main.tsx
Labels: bug, frontend

#260 Add react qr reader facing mode
  libs/client/ui/pages/src/lib/scan/scan.tsx
Labels: bug, frontend

#252 Add detail page loaders
  libs/client/ui/components/src/lib/exercise-card/exercise-card.tsx
  libs/client/ui/pages/src/lib/exercise-detail/exercise-detail.tsx
  libs/client/ui/pages/src/lib/park-detail/park-detail.tsx
Labels: frontend, refactoring
