Repository bregenz-bewegt/bregenz-bewegt, pull requests merged in 2023-02, with the labels that each got.

#314 Add app icon
  apps/client/src/assets/icon/favicon.ico
  apps/client/src/assets/icon/favicon.png
  apps/client/src/assets/icon/icon.png
Labels: enhancement, frontend

#322 Disable guest chat fab in header
  .gitattributes
  libs/client/ui/components/src/lib/header/header.tsx
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
Labels: bug, frontend

#233 Disable analytics guest
  libs/client/ui/components/src/lib/guest-lock/guest-lock.scss
  libs/client/ui/pages/src/lib/analytics/analytics.scss
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.scss
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
  libs/client/ui/pages/src/lib/profile/profile.scss
  libs/server/controllers/activity/src/lib/activity.controller.ts
Labels: bug, enhancement, frontend

#317 Backend passwort requirement check
  libs/shared/types/src/lib/dto/auth/change-password.dto.ts
  libs/shared/types/src/lib/dto/auth/register.dto.ts
  libs/shared/types/src/lib/dto/auth/reset-password.dto.ts
Labels: bug, backend

#316 Landing page favicon
  apps/landing-page/src/favicon.ico
Labels: enhancement, frontend

#313 Privacy police link on register page
  libs/client/ui/pages/src/lib/profile/privacy-police/privacy-police.tsx
  libs/client/ui/pages/src/lib/profile/profile.tsx
  libs/client/ui/pages/src/lib/register/register.tsx
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
  libs/client/ui/router/src/lib/public-outlet/public-outlet.tsx
  libs/landing-page/components/src/lib/footer/footer.tsx
  libs/shared/ui/components/src/lib/privacy-police-content/privacy-police-content.scss
Labels: enhancement, frontend

#326 Remove ToS note on register page
  libs/client/ui/pages/src/lib/register/register.tsx
Labels: frontend, refactoring

#332 Rename reward coin mentions
  libs/client/ui/components/src/lib/title-banner/title-banner.tsx
  libs/client/ui/pages/src/lib/onboarding/slides/earn/earn.tsx
Labels: frontend, refactoring

#330 Fix Mirror QR Scan camera
  libs/client/ui/pages/src/lib/scan/scan.tsx
Labels: bug, frontend

#328 Rewrite analytics guest lock hint
  libs/client/ui/pages/src/lib/analytics/analytics.tsx
Labels: bug, frontend

#324 Redirect guest forbidden routes
  libs/client/ui/components/src/lib/index.ts
  libs/client/ui/components/src/lib/role-route-guard/role-route-guard.tsx
  libs/client/ui/components/src/lib/route-guard/route-guard.scss
  libs/client/ui/router/src/lib/private-tabs-outlet/private-tabs-outlet.tsx
Labels: bug, frontend, security

#348 Competitor Detail Hotfix
  libs/client/ui/pages/src/lib/leaderboard/leaderboard.tsx
Labels: bug, frontend
